set_property PACKAGE_PIN P17 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1]

set_property PACKAGE_PIN R1 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

#OV7725 Data signals
set_property PACKAGE_PIN A18 [get_ports {OV7725_D[7]}]
set_property PACKAGE_PIN B18 [get_ports {OV7725_D[6]}]
set_property PACKAGE_PIN A14 [get_ports {OV7725_D[5]}]
set_property PACKAGE_PIN A13 [get_ports {OV7725_D[4]}]
set_property PACKAGE_PIN A16 [get_ports {OV7725_D[3]}]
set_property PACKAGE_PIN A15 [get_ports {OV7725_D[2]}]
set_property PACKAGE_PIN B17 [get_ports {OV7725_D[1]}]
set_property PACKAGE_PIN B16 [get_ports {OV7725_D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7725_D[0]}]

#OV7725 Control signals
set_property PACKAGE_PIN F13 [get_ports OV7725_XCLK]
set_property PACKAGE_PIN F14 [get_ports OV7725_PCLK]
set_property PACKAGE_PIN B13 [get_ports OV7725_HREF]
set_property PACKAGE_PIN B14 [get_ports OV7725_VSYNC]
set_property PACKAGE_PIN D14 [get_ports OV7725_SIOD]
set_property PACKAGE_PIN C14 [get_ports OV7725_SIOC]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_HREF]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_SIOC]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_SIOD]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_VSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports OV7725_XCLK]
#IIC port"OV7725_SIOD" must be pulled up
set_property PULLUP true [get_ports OV7725_SIOD]
#Whatsthis
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets OV7725_PCLK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets OV7725_VSYNC]

#super_stop_watch
set_property PACKAGE_PIN D4 [get_ports {sseg0[0]}]
set_property PACKAGE_PIN E3 [get_ports {sseg0[1]}]
set_property PACKAGE_PIN D3 [get_ports {sseg0[2]}]
set_property PACKAGE_PIN F4 [get_ports {sseg0[3]}]
set_property PACKAGE_PIN F3 [get_ports {sseg0[4]}]
set_property PACKAGE_PIN E2 [get_ports {sseg0[5]}]
set_property PACKAGE_PIN D2 [get_ports {sseg0[6]}]
set_property PACKAGE_PIN H2 [get_ports {sseg0[7]}]
set_property PACKAGE_PIN B4 [get_ports {sseg1[0]}]
set_property PACKAGE_PIN A4 [get_ports {sseg1[1]}]
set_property PACKAGE_PIN A3 [get_ports {sseg1[2]}]
set_property PACKAGE_PIN B1 [get_ports {sseg1[3]}]
set_property PACKAGE_PIN A1 [get_ports {sseg1[4]}]
set_property PACKAGE_PIN B3 [get_ports {sseg1[5]}]
set_property PACKAGE_PIN B2 [get_ports {sseg1[6]}]
set_property PACKAGE_PIN D5 [get_ports {sseg1[7]}]
set_property PACKAGE_PIN G6 [get_ports {en0[0]}]
set_property PACKAGE_PIN E1 [get_ports {en0[1]}]
set_property PACKAGE_PIN F1 [get_ports {en0[2]}]
set_property PACKAGE_PIN G1 [get_ports {en0[3]}]
set_property PACKAGE_PIN H1 [get_ports {en1[0]}]
set_property PACKAGE_PIN C1 [get_ports {en1[1]}]
set_property PACKAGE_PIN C2 [get_ports {en1[2]}]
set_property PACKAGE_PIN G2 [get_ports {en1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[7]}]

set_property PACKAGE_PIN K2 [get_ports {signal0}]
set_property IOSTANDARD LVCMOS33 [get_ports {signal0}]